// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Infrastructure {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Infrastructure.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ShoppingListItemMissingMessage {
            get {
                return ResourceManager.GetString("ShoppingListItemMissingMessage", resourceCulture);
            }
        }
        
        public static string ShoppingListItemMissingTitle {
            get {
                return ResourceManager.GetString("ShoppingListItemMissingTitle", resourceCulture);
            }
        }
        
        public static string ShoppingListItemMissingConfirm {
            get {
                return ResourceManager.GetString("ShoppingListItemMissingConfirm", resourceCulture);
            }
        }
        
        public static string ShoppingListItemNamePlaceholder {
            get {
                return ResourceManager.GetString("ShoppingListItemNamePlaceholder", resourceCulture);
            }
        }
        
        public static string ShoppingListItemAmountPlaceholder {
            get {
                return ResourceManager.GetString("ShoppingListItemAmountPlaceholder", resourceCulture);
            }
        }
        
        public static string ShoppingListItemConfirmTitle {
            get {
                return ResourceManager.GetString("ShoppingListItemConfirmTitle", resourceCulture);
            }
        }
        
        public static string ReceiptUnknonwnErrorMessage {
            get {
                return ResourceManager.GetString("ReceiptUnknonwnErrorMessage", resourceCulture);
            }
        }
        
        public static string ReceiptUnknonwnErrorTitle {
            get {
                return ResourceManager.GetString("ReceiptUnknonwnErrorTitle", resourceCulture);
            }
        }
        
        public static string ReceiptUnknonwnErrorConfirm {
            get {
                return ResourceManager.GetString("ReceiptUnknonwnErrorConfirm", resourceCulture);
            }
        }
    }
}
